config/routes.rb
Rails.application.routes.draw do
  mount LikeDislike::Engine, at: '/'
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "static_pages#home"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users, only: [:index, :show]
  resources :locations, only: [:index, :show]
  resources :reviews
  resources :comments
  resources :votes, only: [:create, :destroy]
  resources :categories, only: :show
  resources :relationships, only: [:create, :destroy]
  resources :requests, except: [:edit, :update]
  namespace :admin do
    root "static_pages#home"
    resources :locations
    resources :users, only: [:index, :destroy, :show]
    resources :categories
    resources :images, only: [:new, :create]
    resources :requests, except: [:create, :new, :edit]
  end
end

app/models/location.rb
class Location < ApplicationRecord
  include PublicActivity::Model
  tracked only: [:create, :destroy],
    owner: ->controller, model{controller && controller.current_user}

  belongs_to :category

  has_many :reviews, dependent: :destroy
  has_many :images, dependent: :destroy

  mount_uploader :picture, PictureUploader

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :name, length: {maximum: 150}, presence: true
  validates :category_id, presence: false
  validates :rate_avg, presence: true,format: {with: /\A\d+(?:.\d{0,2})?\z/},
    numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 5}
  validate  :picture_size

  scope :best_book, -> do
    order("rate_avg DESC").limit(5)
  end

  before_save :update_rating

  UNRANSACKABLE_ATTRIBUTES = ["id", "updated_at", "created_at", "introduction", "picture", "address", "latitude", "longitude"]

  def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end

  def update_rate_avg
    if self.reviews.size > 0
      @value =  self.reviews.average :rating
      update_attributes rate_avg: @value.to_f.round(2)
    end
  end

  def rating
    self.reviews.count > 0 ? self.reviews.average(:rating) : 0
  end

  private
  def picture_size
    if picture.size > 5.megabytes
      errors.add :picture, I18n.t(:picturesize)
    end
  end

  def update_rating
    self[:rate_avg] = rating
  end
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < ApplicationController
  load_and_authorize_resource

  def index
    @search = Location.search(params[:q])
    @locations = @search.result.page(params[:page]).per_page(5)
    @search.build_condition
  end

  def show
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new location_params
    if @location.save
      flash[:success] = t :success
      redirect_to admin_category_path @location.category
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @location.update_attributes location_params
      flash[:success] = t :locationupdated
      redirect_to admin_locations_path
    else
      render :edit
    end
  end

  def destroy
    @location.destroy
    flash[:danger] = t :destroyed
    redirect_to admin_locations_path
  end

  private
  def location_params
    params.require(:location).permit :name, :introduction, :category_id,
      :picture, :address, :rate_avg
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  load_and_authorize_resource

  def index
    @search = Location.search(params[:q])
    @locations = @search.result.page(params[:page]).per_page(6)
    @categories = Category.all
  end

  def show
    @location = Location.find_by_id params[:id]
    @review = Review.new
    @reviews = @location.reviews.all.page(params[:page]).per_page(3)
    @comment = Comment.new
  end
end

app/views/admin/locations/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select associations: [:category] %>
  <% end %>
  <%= f.predicate_select %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</div>

app/views/admin/locations/_location_form.html.erb
<%= form_for [:admin, @location], html: {multipart: true} do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :introduction %>
    <%= f.text_field :introduction, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div class="form-group">
    <%= f.file_field :picture, accept: "image/jpeg, image/gif, image/png" %>
  </div>

  <%= f.submit t(:submit), class: "btn btn-primary" %>
<% end %>

app/views/admin/locations/edit.html.erb
<% provide :title, t("editlocation") %>
<h1><%= t :editlocation %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "location_form" %>
  </div>
</div>

app/views/admin/locations/index.html.erb
<% provide :title, t("alllocations") %>
<h1><%= t :alllocations %></h1>

<div class="col-lg-4 col-lg-offset-5">
  <div class="center form-group">
    <%= link_to t("newlocation"), new_admin_location_path,
      class: "btn btn-primary btn-lg" %>
  </div>
</div>

<div class="col-sm-6 col-sm-offset-3">
  <%= search_form_for [:admin, @search], class: "form-inline" do |f| %>
    <%= f.condition_fields do |c| %>
      <%= render "condition_fields", f: c%>
    <% end %>
    <p><%= link_to_add_fields "Add Conditions", f, :condition %>
    <div class="actions"><%= f.submit "Search" %></div>
<% end %>
</div>

<div class="col-sm-6 col-sm-offset-3">
  <div class="row">
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= sort_link(@search, :name, "Name") %></th>
          <th><%= sort_link(@search, :category_name, "Category") %></th>
          <th><%= sort_link(@search, :rating, "Rating") %></th>
          <th>Introduction</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @locations.each do |location| %>
          <tr>
            <td><%= link_to location.name, location_path(location) %></td>
            <td><%= link_to location.category.name,
              admin_category_path(location.category) %></td>
            <td><%= location.rate_avg %></td>
            <td><%= location.introduction %></td>
            <td>
              <%= link_to t(:editlocation), edit_admin_location_path(location),
                class: "btn btn-primary" %>
            </td>
            <td>
              <%= link_to t(:delete), [:admin, location],
                method: :delete, data: {confirm: t(:areyousure)},
                class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @locations, theme: 'twitter-bootstrap-3' %>
  </div>
</div>

app/views/admin/locations/new.html.erb
<% provide :title, t("createlocation") %>
<h1><%= t :createlocation %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "location_form" %>
    <%= link_to "New Image", new_admin_image_path,
      class: "btn btn-primary", id:"form-btn" %>
  </div>
</div>

app/views/admin/locations/show.html.erb
<div id="location-show">
  <div class="page-header text-center">
    <h1><%= @location.name %></h1>
  </div>
  <div class="content-section-a container">
    <div class="row">
      <div class="text-center">
        <h2>Introduction</h2>
        <h3><%= @location.introduction %></h3>
      </div>
    </div>
  </div>
  <div class="content-section-b container">
    <h2>Picture</h2>
    <div id="slider-thumb">
      <ul>
        <% @location.images.each do |image| %>
          <li class="col-sm-4 img-responsive">
            <a class="thumbnail" id="carousel-selector-<%= image.id %>">
              <%= cl_image_tag image.img_url(:thumbnail)%>
            </a>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col-xs-12" id="slider">
      <div class="row">
        <div class="col-sm-12" id="myCarousel">
          <div class="carousel-inner">
            <div class="active item" data-slide-number="0">
              <%= cl_image_tag @location.picture_url :thumbnail %>
            </div>
            <% @location.images.each do |image| %>
              <div class="item" data-slide-number="<%= image.id %>">
                <%= cl_image_tag image.img_url %>
              </div>
            <% end %>            
          </div>
          <a class="left carousel-control" href="#myCarousel"
            role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
          </a>
        </div>
      </div>
    </div>
  </div>
  <div class="content-section-a container">
    <h2>Review</h2>
    <%= image_tag "http://maps.google.com/maps/api/staticmap?size=1450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>
  </div>
</div>