config/routes.rb
Rails.application.routes.draw do
  mount LikeDislike::Engine, at: '/'
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "static_pages#home"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users, only: [:index, :show]
  resources :locations, only: [:index, :show]
  resources :reviews
  resources :comments
  resources :votes, only: [:create, :destroy]
  resources :categories, only: :show
  resources :relationships, only: [:create, :destroy]
  resources :requests, except: [:edit, :update]
  namespace :admin do
    root "static_pages#home"
    resources :locations
    resources :users, only: [:index, :destroy, :show]
    resources :categories
    resources :images, only: [:new, :create]
    resources :requests, except: [:create, :new, :edit]
  end
end

app/views/shared/_activity_owner.html.erb
<% if current_user_activity_owner? a %>
  <%= t :you %>
<% else %>
  <%= link_to a.owner.name, admin_user_path(a.owner) %>
<% end %>

app/views/shared/_comment_form.html.erb
<%= form_for @comment, remote: true do |f| %>
  <div class="row">
    <div class="col-md-8">
      <%= f.hidden_field :review_id, value: review.id %>
      <%= f.text_area :content, rows: 3, placeholder: t(:addcomment), class: "form-control form-margin",
        id: "comment_content_#{review.id}" %>
    </div>
    <div class="col-md-2" style="margin-top: 40px;">
      <%= f.submit t(:submitcomment), class: "btn btn-primary"%>
    </div>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <span><%= t :theform %></span> <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_review_form.html.erb
<%= form_for @review do |f| %>
  <div class="form-review">
    <div class="row">
      <%= f.hidden_field :location_id, value: location.id %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :rating, value: 0 %>

      <div id="rating-form">
        <label>Rating: </label>
      </div>
      
      <%= f.text_area :content, rows: 7, placeholder: t(:addreview), class: "form-control form-margin",
          id: "review_content_#{location.id}" %>
      <%= f.submit t(:submitreview), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/shared/_show_location.html.erb
<div class="row blog-post post-list col-md-8 col-md-offset-1">
  <div class="thumbnail box-top">
    <div class="row clickable-row" data-href="<%= location_path location %>">
      <div class="col-md-5">
        <%= image_tag location.picture.url, alt: t("locationalt"), class:
        "img-responsive img-thumbnail", width: 300, height: 200 %>
      </div>
      <div class="caption col-md-7">
        <div class="item-info">
          <h3 class="clickable-row" data-href="<%= location_path location %>">
            <%= link_to location.name, location_path(location) %>
          </h3>
          <h6>Systems created about ⚬ <%= location.created_at.strftime t(:timetype) %></h6>
          <h4 class="clickable-row" data-href="<%= location_path location %>">
            <%= location.introduction %>
          </h4>
          <span class="col-md-offset-9">
            <td class="clickable-row" data-href="<%= location_path location %>">
              <%= link_to t(:Review), location_path(location), class: "btn btn-primary" %>
            </td>
          </span>
        </div>
      </div>
    </div>
    <div class="mini-post-list col-md-offset-0">
      <td class="clickable-row" data-href="<%= location_path location %>"> 
      <i class="glyphicon glyphicon-heart-empty"></i>&nbsp;<%= location.rate_avg.round(2) %>
      </td> ⚬
      <span id="review_count">
        <i class="glyphicon glyphicon-pencil"></i>&nbsp;<%= location.reviews.count %>
      </span>
    </div>
  </div>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>