config/routes.rb
Rails.application.routes.draw do
  mount LikeDislike::Engine, at: '/'
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "static_pages#home"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users, only: [:index, :show]
  resources :locations, only: [:index, :show]
  resources :reviews
  resources :comments
  resources :votes, only: [:create, :destroy]
  resources :categories, only: :show
  resources :relationships, only: [:create, :destroy]
  resources :requests, except: [:edit, :update]
  namespace :admin do
    root "static_pages#home"
    resources :locations
    resources :users, only: [:index, :destroy, :show]
    resources :categories
    resources :images, only: [:new, :create]
    resources :requests, except: [:create, :new, :edit]
  end
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user

  validates :content, presence: true, length: {maximum: 400}

  enum status: [:waitting, :denied, :accepted]

  scope :accepted, ->{where status: :accepted}
end

app/controllers/admin/requests_controller.rb
class Admin::RequestsController < ApplicationController
  load_and_authorize_resource

  def index
    @requests = (Request.order created_at: :desc)
      .page(params[:page]).per_page(10)
  end

  def show
  end

  def update
    @request = Request.find params[:id]
    if @request.update_attributes status: params[:status]
      if @request.accepted?
        flash[:info] = t "requests.accepted"
      else
        flash[:info] = "requests.denied"
      end
    else
      flash[:warning] = t "requests.update_fail"
    end
    redirect_to admin_requests_path
  end

  def destroy
    @request = Request.find(params["id"])
    if @request.destroy
      flash[:success] = t "requests.destroy"
    else
      flash[:error] = t "requests.destroy_fail"
    end
    redirect_to admin_requests_path
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  load_and_authorize_resource
  before_action :load_requests, only: [:index]

  def index
  end

  def show
  end

  def new
    @request = Request.new
  end

  def create
    @request = Request.new request_params
    if @request.save
      flash[:success] = t "requests.success"
      redirect_to requests_path
    else
      render :new
    end
  end

  def destroy
    if @request.destroy
      flash[:success] = t "requests.destroy"
    else
      flash[:error] = t "requests.destroy_fail"
    end
    redirect_to requests_path
  end

  private
  def request_params
    params.require(:request).permit :user_id, :content
  end

  def load_requests
    @requests = (current_user.requests.order created_at: :desc)
      .page(params[:page]).per_page(10)
  end
end

app/views/requests/_request.html.erb
<% @requests.each_with_index do |request, index| %>
  <tr>
    <th scope="row"><%= index + 1 %></th>
    <td><%= request.content.truncate 70 %></td>
    <td><%= request.created_at.strftime t(:time_type) %></td>
    <td><%= request.status %></td>
    <td>
      <%= link_to "", request_path(request),
        class: "glyphicon glyphicon-log-in" %>
      <%= link_to "", request_path(request),
        method: :delete, data: {confirm: t("confirm_rq")},
        class: "glyphicon glyphicon-remove" %>
    </td>
  </tr>
<% end %>

app/views/requests/index.html.erb
<div class="col-md-10 cod-md-offset-1 ">
  <div class="row">
    <%= link_to t("Add Request"), new_request_path,
      class: "btn btn-primary" %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th><%= t "Index" %></th>
          <th><%= t "Content" %></th>
          <th><%= t "Time Create" %></th>
          <th><%= t "Status" %></th>
          <th></th>
        </tr>
      </thead>
      <tbody id="requests-body">
        <%= render "request" %>
      </tbody>
    </table>
    <%= paginate @requests %>
  </div>

</div>

app/views/requests/new.html.erb
<div class="container-fluid well boxshadow">
  <h2><%= t "requests.title" %></h2>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <%= form_for current_user.requests.build do |f| %>
        <%= render "shared/error_messages", object: @request %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="form-group">
          <%= f.text_area :content, class: "form-control",
            placeholder: t("requests.content"), rows: 20 %>
        </div>
        <div class="actions text-center">
          <%= f.submit t("requests.sent"), class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/requests/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-1">
    <h3><%= t "requests.show.title" %></h3>
    <p style="word-wrap: break-word"><%= @request.content %></p>
    <span><%= link_to "", requests_path,
      class: "glyphicon glyphicon-circle-arrow-left" %></span>
  </div>
</div>