config/routes.rb
Rails.application.routes.draw do
  mount LikeDislike::Engine, at: '/'
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "static_pages#home"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users, only: [:index, :show]
  resources :locations, only: [:index, :show]
  resources :reviews
  resources :comments
  resources :votes, only: [:create, :destroy]
  resources :categories, only: :show
  resources :relationships, only: [:create, :destroy]
  resources :requests, except: [:edit, :update]
  namespace :admin do
    root "static_pages#home"
    resources :locations
    resources :users, only: [:index, :destroy, :show]
    resources :categories
    resources :images, only: [:new, :create]
    resources :requests, except: [:create, :new, :edit]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  include PublicActivity::Model
  tracked owner: ->controller, model{controller && controller.current_user}

  has_many :locations, dependent: :destroy

  validates :name, length: {maximum: 150}, uniqueness: true
  
  UNRANSACKABLE_ATTRIBUTES = ["id", "updated_at", "created_at", "category"]

  def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :find_category, only: [:show, :destroy, :edit, :update]

  def index
    @search = Category.search(params[:q])
    @categories = @search.result.page(params[:page]).per_page(10)
  end

  def show
    @search = @category.locations.search params[:q]
    @locations = @search.result.page params[:page ]
  end

  def edit
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t :success
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_path
  end

  def update
    if @category.update category_params
      flash[:success] = t "categories.update"
    else
      flash[:danger] = t "flash.fail"
    end
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit :name
  end

  def find_category
    @category = Category.find_by_id params[:id]
    if @category.nil?
      flash[:danger] = t :category_fails
      redirect_to admin_categories_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    load_and_authorize_resource

  def show
    @locations = @category.locations.order(created_at: :desc).paginate page: params[:page]
  end
end

app/views/admin/categories/_category.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @category] do |f| %>
      <%= render "shared/error_messages", object: @category %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.submit t("categories.edit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/categories/edit.html.erb
<% provide :title, t("categories.edit") %>
<h1><%= t "categories.edit" %></h1>
<%= render "category" %>

app/views/admin/categories/index.html.erb
<% provide :title, t(:all_categories) %>
<h1><%= t :all_categories %></h1>
<div class="col-lg-4 col-lg-offset-5">
  <div class="center form-group">
    <%= link_to t(:newcategory), new_admin_category_path, class: "btn btn-primary" %>
  </div>
</div>
<div class="col-sm-6 col-sm-offset-3">
  <%= search_form_for [:admin, @search], class: "form-inline" do |f| %>
    <div class="form-group">
        <%= f.label :name_cont, 'Category Name:' %>
        <%= f.text_field :name_cont, class: "form-control" %><br>
    </div>
    <%= f.submit 'Search', class: "btn btn-default" %>
<% end %>
</div>
<% if can? :manage, @users %>
<div class="col-sm-6 col-sm-offset-3">
  <div class="row">
    <table class="table table-striped">
    <thead>
      <th><%= sort_link(@search, :name, "Name") %></th>
      <th><%= t "category.created_at" %></th>
      <th><%= t "category_id.update_at" %></th>
      <th>Action</th>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td ><%= link_to category.name, admin_category_path(category) %></td>
          <td><%= category.created_at.strftime t "time_format" %></td>
          <td><%= category.updated_at.strftime t "time_format" %></td>
          <td class="dn-action-padding">
            <%= link_to t(:edit), edit_admin_category_path(category),
              class: "btn btn-primary" %>
            <%= link_to t(:delete), [:admin, category], method: :delete,
              data: {confirm: t(:sure)}, class: "btn btn-danger btn-primary" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @categories, theme: 'twitter-bootstrap-3' %>
<% end %>

app/views/admin/categories/new.html.erb
<% provide :title, t(:new_category) %>
<h1><%= t :new_category %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @category] do |f| %>
      <%= render "shared/error_messages", object: @category %>

      <%= f.label t(:name) %>
      <%= f.text_field :name, placeholder: t(:compose_title_new_category),
        class: "form-control" %>

      <%= f.submit t(:create_category), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/categories/show.html.erb
<% provide :title, @category.name %>
<div class="col-sm-3">
  <h1><%= @category.name %></h1>
  <small><%= t "categories.number" %> : <%= @category.locations.count %></small>
  <br>
  <%= link_to t("newlocation"), new_admin_location_path, class: "btn btn-success" %>
</div>
<div class="col-sm-9">
  <h3><%= t "location.list" %></h3>

  <table class="table table striped">
    <thead>
      <tr>
        <th><%= sort_link(@search, :name, "Location") %></th>
        <th><%= t "category.created_at" %></th>
        <th><%= t "category_id.update_at" %></th>
        <th><%= t "location.action" %></th>
      </tr>
    </thead>
    <tbody>
      <% @locations.each do |location| %>
        <tr>
          <td><%= link_to location.name, location_path(location) %></td>
          <td><%= location.created_at.strftime t "time_format" %></td>
          <td><%= location.updated_at.strftime t "time_format" %></td>
          <td>
            <%= link_to t("button.edit"), edit_admin_location_path(location),
              class: "btn btn-success" %>
            <%= link_to t("button.delete"), admin_location_path(location),
              method: :delete, data: {confirm: t("flash.confirm")},
              class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>